# 1. 강의영상

In [ ]:
# {{<video https://youtu.be/playlist?list=PLQqh36zP38-x6P7VsPJG0cqNkbJTII5yR&si=HhIbz4gH711kw7Dx >}}

# 2. Imports

In [ ]:
import torch
import matplotlib.pyplot as plt

# 3. 환경셋팅

`-` 코랩이용자: 별도의 설치 필요 없음

### - **GPU 관리가 꼭 필요함!! (시험하루전날 수업 몰아서 듣지않기, 아이디만들어두기) 강의를 미리미리 들어야지 gpu를 덜 써서 다음날 gpu가 블락될 위험이 줄어듦...  꼭 강의는 미리 들어서 시험 전날엔 gpu 쓰지 말자**
- 특히 시험기간에 조심하세요

`-` 리눅스서버 사용자 (ref: <https://pytorch.org/get-started/locally/>)

```bash
conda create -n dl2025 python=3.9
conda activate dl2025
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
```

# 4. 필요한 지식

`-` 선형대수학

- 벡터와 행렬
- 행렬의 곱셉
- 트랜스포즈

`-` 기초통계학(수리통계)

- 정규분포, 이항분포
- 모수, 추정
- $X_i \overset{i.i.d.}{\sim} N(0,1)$


`-` 회귀분석

- 독립변수($y$), 설명변수($X$)
- ${\boldsymbol y} = {\bf X}{\boldsymbol \beta} + {\boldsymbol \epsilon}$

`-` 파이썬

- 파이썬 기본문법
- 넘파이, 판다스
- 전반적인 클래스 지식 (`__init__`, `self`, ...)
- 상속

# 5. 예비학습

## A. torch

`-` 벡터

In [ ]:
torch.tensor([1,2,3]) #벡터

tensor([1, 2, 3])

`-` 벡터의 덧셈

In [ ]:
torch.tensor([1,2,3]) + torch.tensor([2,2,2]) #벡터의 같은 위치끼리 더해진다

tensor([3, 4, 5])

`-` 브로드캐스팅

In [ ]:
torch.tensor([1,2,3]) + 2 #벡터 [1,2,3]에다가 2를 다 더해준다. 수학적 표현이 아니지만 가능함 - 브로드캐스팅

tensor([3, 4, 5])

## B. 벡터와 매트릭스

`-` $3 \times 2$ matrix

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) #3x2 행렬

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`-` $3 \times 1$ matrix = $3 \times 1$ column vector

In [ ]:
torch.tensor([[1],[3],[5]]) #3x1 행렬 (컬럼벡터, 열벡터)

tensor([[1],
        [3],
        [5]])

`-` $1 \times 2$ matrix = $1 \times 2$ raw vector

In [ ]:
torch.tensor([[1,2]]) #1x2 행렬 (로우벡터, 행벡터)

tensor([[1, 2]])

`-` 더하기

***브로드캐스팅(편한거)***

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) - 1 #모든 원소를 1씩 뺀다

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-3],[-5]]) #3x2 행렬에서 3x1 행렬 뺄셈

tensor([[0, 1],
        [0, 1],
        [0, 1]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-2]]) #3x2행렬에서 1x2행렬 뺄셈. 여기서 1x2 행렬이 3x2행렬에 맞게 3x2가 되고 -1과 -2가 밑으로 두 줄 더 생긴다.

tensor([[0, 0],
        [2, 2],
        [4, 4]])

***잘못된 브로드캐스팅***

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-3,-5]]) #3x2행렬에서 1x3행렬을 뺀다는 것. 1x3행렬에서 -1,-3,-5가 밑으로 두 줄 채워져서 3x3행렬이 되고, 3x2와 차원이 맞지 않는다.

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-2]]) #3x2행렬에서 2x1행렬을 뺀다는 것. 2x1에서 옆으로 -1과 -2가 채워진다고 해도 3x2와 차원이 맞지 않게 된다.

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

***이상한 것***

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-2]) #3x2행렬에서 벡터를 빼는 것. torch에서 계산이 지원됨. 벡터 (-1,-2)가 열벡터로 알아서 해석하고(1x2행렬로 해석) 계산이 됨.

tensor([[0, 0],
        [2, 2],
        [4, 4]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-3,-5]) #3x2행렬에서 벡터를 빼는 것. 이건 안됨.

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

`-` 행렬곱

***정상적인 행렬곱***

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([[1],[2]]) #@는 행렬곱 기호. 3x2행렬과 2x1행렬 곱하기

tensor([[ 5],
        [11],
        [17]])

In [ ]:
torch.tensor([[1,2,3]]) @ torch.tensor([[1,2],[3,4],[5,6]]) #1x3행렬과 3x2행렬 곱하기

tensor([[22, 28]])

***잘못된 행렬곱***

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([[1,2]]) #3x2 행렬과 1x2행렬을 곱하기 -> 차원이 안맞아서 실패

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 1x2)

In [ ]:
torch.tensor([[1],[2],[3]]) @ torch.tensor([[1,2],[3,4],[5,6]]) #3x1행렬과 3x2행렬 곱하기 -> 차원이 안맞아서 실패

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x1 and 3x2)

***이상한 것***

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([1,2]) # 이게 왜 가능..
#3x2행렬과 길이가 2인 벡터 곱셈 -> 벡터를 알아서 2x1 행렬로 받아들이고(로우벡터) 계산을 해준다.

tensor([ 5, 11, 17])

In [ ]:
torch.tensor([1,2,3]) @ torch.tensor([[1,2],[3,4],[5,6]]) # 이건 왜 가능?
#길이(차원)이 3인 벡터와 3x2행렬 곱셈 -> 알아서 컬럼벡터로 받아서 1x3행렬로 맞춘 뒤 계산을 해준다.

tensor([22, 28])

## C. transpose, reshape

`-` transpose

In [ ]:
torch.tensor([[1,2],[3,4]]).T #2x2행렬의 transpose.

tensor([[1, 3],
        [2, 4]])

In [ ]:
torch.tensor([[1],[3]]).T #2x1행렬의 transpose -> 1 밑에 3이 있는 형태에서 transpose되면 밑에 있던 3이 1 오른쪽으로 이동. 로우벡터가 된다.

tensor([[1, 3]])

In [ ]:
torch.tensor([[1,2]]).T #바로 위랑 반대 예시

tensor([[1],
        [2]])

`-` reshape

***일반적인 사용***

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,3) #3x2행렬의 차원 바꾸기. reshape이 transpose기능이랑 같음

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(6,1) #3x2행렬 차원 바꾸기.

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(1,6) #3x2행렬 차원 바꾸기.

tensor([[1, 2, 3, 4, 5, 6]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(6) #길이가 6인 벡터로 바꿔라.

tensor([1, 2, 3, 4, 5, 6])

***편한 것***

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,-1) #(줄 개수, 그 줄에 올 숫자 개수) 형태이고, 줄 개수와 숫자 개수가 곱해지면 총 숫자 개수가 나와야 함. 숫자를 제대로 못 맞추면 에러가 남.
#숫자 개수 모르겠으면 -1을 적으면 알아서 맞춰준다

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(6,-1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(-1,6) #줄 개수 모르겠으면 숫자 개수만 적고 줄 개수에 -1 적어주면 알아서 맞춰준다

tensor([[1, 2, 3, 4, 5, 6]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(-1) #일자로 쭉 피는 것

tensor([1, 2, 3, 4, 5, 6])

## D. concat, stack $(\star\star\star)$

`-` concat : 양 옆으로 붙이고 싶은 행렬 두 개를 리스트에 적어주고, 축을 표시해준다.

In [ ]:
a = torch.tensor([[1],[3],[5]])
b = torch.tensor([[2],[4],[6]])
torch.concat([a,b],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a

tensor([[1],
        [3],
        [5]])

In [ ]:
b

tensor([[2],
        [4],
        [6]])

`-` stack : 차원을 늘려서 행렬을 붙인다.

In [ ]:
a = torch.tensor([1,3,5])
b = torch.tensor([2,4,6])
torch.stack([a,b],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a

tensor([1, 3, 5])

In [ ]:
b

tensor([2, 4, 6])

In [ ]:
a.reshape(3,1)

tensor([[1],
        [3],
        [5]])

In [ ]:
torch.concat([a.reshape(3,1),b.reshape(3,1)],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

:::{.callout-warning}

concat과 stack을 지금 처음본다면 아래를 복습하시는게 좋습니다.

<https://guebin.github.io/PP2024/posts/06wk-2.html#numpy와-축axis>
:::